# Configurações do Banco de Dados SQLite
spring.datasource.url=jdbc:sqlite:banco/album.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Força o Hibernate a usar a SUA classe customizada de Dialeto
spring.jpa.database-platform=album_dinossauros.SQLiteDialect

# Configurações de Inicialização e Logs do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desativação de Cache para Desenvolvimento
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0

# Limites de Upload de Arquivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Define o tamanho máximo permitido para um único arquivo de upload
spring.servlet.multipart.max-file-size=10MB

# Define o tamanho máximo permitido para a requisição inteira (form + imagem)
spring.servlet.multipart.max-request-size=10MB